source 'http://rubygems.org'

gem 'rails', '3.0.20'

gem 'mysql2', '~> 0.2.11'
gem 'jbuilder'
gem 'rails-i18n'
gem 'jquery-rails'
gem 'devise'
gem 'faker'
gem 'will_paginate', '~> 3.0'
gem 'spreadsheet'


