CREATE TABLE `calificacion` (
  `ID` int(11) NOT NULL,
  `CLASE_ID` int(11) NOT NULL,
  `ESTUDIANTE_ID` int(11) NOT NULL,
  `COMENTARIO` varchar(500) COLLATE latin1_spanish_ci DEFAULT NULL,
  `NOTA` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`,`CLASE_ID`,`ESTUDIANTE_ID`),
  KEY `fk_CALIFICACION_CLASE1` (`CLASE_ID`),
  KEY `fk_CALIFICACION_ESTUDIANTE1` (`ESTUDIANTE_ID`),
  CONSTRAINT `fk_CALIFICACION_CLASE1` FOREIGN KEY (`CLASE_ID`) REFERENCES `clase` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CALIFICACION_ESTUDIANTE1` FOREIGN KEY (`ESTUDIANTE_ID`) REFERENCES `estudiante` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;

CREATE TABLE `clase` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SECCION_ID` int(11) NOT NULL,
  `PROFESOR_ID` int(11) NOT NULL,
  `HORARIO_ID` int(11) NOT NULL,
  `MATERIA_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`,`SECCION_ID`,`PROFESOR_ID`,`HORARIO_ID`,`MATERIA_ID`),
  KEY `fk_CLASE_SECCION1` (`SECCION_ID`),
  KEY `fk_CLASE_PROFESOR1` (`PROFESOR_ID`),
  KEY `fk_CLASE_HORARIO1_idx` (`HORARIO_ID`),
  KEY `fk_CLASE_CATALOGO_MATERIAS1_idx` (`MATERIA_ID`),
  CONSTRAINT `fk_CLASE_CATALOGO_MATERIAS1` FOREIGN KEY (`MATERIA_ID`) REFERENCES `materia` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLASE_HORARIO1` FOREIGN KEY (`HORARIO_ID`) REFERENCES `horario` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLASE_PROFESOR1` FOREIGN KEY (`PROFESOR_ID`) REFERENCES `profesor` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLASE_SECCION1` FOREIGN KEY (`SECCION_ID`) REFERENCES `seccion` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;

CREATE TABLE `clase_estudiante` (
  `CLASE_ID` int(11) NOT NULL,
  `ESTUDIANTE_ID` int(11) NOT NULL,
  `APROBADO` int(1) DEFAULT NULL,
  PRIMARY KEY (`CLASE_ID`,`ESTUDIANTE_ID`),
  KEY `fk_CLASE_has_ESTUDIANTE_ESTUDIANTE1` (`ESTUDIANTE_ID`),
  KEY `fk_CLASE_has_ESTUDIANTE_CLASE` (`CLASE_ID`),
  CONSTRAINT `fk_CLASE_has_ESTUDIANTE_CLASE` FOREIGN KEY (`CLASE_ID`) REFERENCES `clase` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLASE_has_ESTUDIANTE_ESTUDIANTE1` FOREIGN KEY (`ESTUDIANTE_ID`) REFERENCES `estudiante` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;

CREATE TABLE `estudiante` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `MATRICULA` varchar(45) COLLATE latin1_spanish_ci DEFAULT NULL,
  `MATRICULA_EXTERNA` varchar(45) COLLATE latin1_spanish_ci DEFAULT NULL,
  `PERSONA_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`,`PERSONA_ID`),
  UNIQUE KEY `MATRICULA_UNIQUE` (`MATRICULA`),
  KEY `fk_ESTUDIANTE_PERSONA1` (`PERSONA_ID`),
  CONSTRAINT `fk_ESTUDIANTE_PERSONA1` FOREIGN KEY (`PERSONA_ID`) REFERENCES `persona` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;

CREATE TABLE `historial` (
  `ID` int(11) NOT NULL,
  `COMENTARIO` varchar(1000) COLLATE latin1_spanish_ci DEFAULT NULL,
  `ESTUDIANTE_ID` int(11) NOT NULL,
  `INSTITUCION_ID` int(11) NOT NULL,
  `TIPO_ID` int(11) NOT NULL COMMENT '\n\nTipo de Historial\nmedico\nescolar\nfamiliar\netc..\n',
  PRIMARY KEY (`ID`,`TIPO_ID`),
  KEY `fk_HISTORIAL_ESTUDIANTE1` (`ESTUDIANTE_ID`),
  KEY `fk_HISTORIAL_INSTITUCION1` (`INSTITUCION_ID`),
  KEY `fk_HISTORIAL_TIPO1` (`TIPO_ID`),
  CONSTRAINT `fk_HISTORIAL_ESTUDIANTE1` FOREIGN KEY (`ESTUDIANTE_ID`) REFERENCES `estudiante` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_HISTORIAL_INSTITUCION1` FOREIGN KEY (`INSTITUCION_ID`) REFERENCES `institucion` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_HISTORIAL_TIPO1` FOREIGN KEY (`TIPO_ID`) REFERENCES `tipo` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;

CREATE TABLE `horario` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `HORA_INICIO` time NOT NULL,
  `HORA_FIN` time NOT NULL,
  `TIPO_ID` int(11) NOT NULL COMMENT '\n\nENUM DE LOS DIAS\n\nLUNES\nMARTES\n',
  PRIMARY KEY (`ID`,`TIPO_ID`),
  KEY `fk_HORARIO_TIPO1` (`TIPO_ID`),
  CONSTRAINT `fk_HORARIO_TIPO1` FOREIGN KEY (`TIPO_ID`) REFERENCES `tipo` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;

CREATE TABLE `institucion` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(45) COLLATE latin1_spanish_ci NOT NULL,
  `DIRECCION` varchar(45) COLLATE latin1_spanish_ci NOT NULL,
  `TELEFONO` varchar(45) COLLATE latin1_spanish_ci DEFAULT NULL,
  `PAIS` varchar(45) COLLATE latin1_spanish_ci DEFAULT NULL,
  `CIUDAD` varchar(45) COLLATE latin1_spanish_ci DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;

CREATE TABLE `materia` (
  `ID` int(11) NOT NULL,
  `TIPO_ID_NOMBRE_MATERIA` int(11) NOT NULL COMMENT 'MATEMATICA 3\nMATEMATICA 1\nESPANOL 2',
  `TIPO_ID_ANO_ACADEMMICA` int(11) NOT NULL,
  PRIMARY KEY (`ID`,`TIPO_ID_NOMBRE_MATERIA`,`TIPO_ID_ANO_ACADEMMICA`),
  UNIQUE KEY `ID_UNIQUE` (`ID`),
  KEY `fk_MATERIA_TIPO1_idx` (`TIPO_ID_NOMBRE_MATERIA`),
  KEY `fk_MATERIA_TIPO2_idx` (`TIPO_ID_ANO_ACADEMMICA`),
  CONSTRAINT `fk_MATERIA_TIPO1` FOREIGN KEY (`TIPO_ID_NOMBRE_MATERIA`) REFERENCES `tipo` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_MATERIA_TIPO2` FOREIGN KEY (`TIPO_ID_ANO_ACADEMMICA`) REFERENCES `tipo` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;

CREATE TABLE `pagos` (
  `ID` int(11) NOT NULL,
  `FECHA_PAGO` date DEFAULT NULL,
  `MONTO` varchar(45) COLLATE latin1_spanish_ci DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;

CREATE TABLE `periodo_academico` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FECHA_INICIAL` date NOT NULL,
  `FECHA_FINAL` date NOT NULL,
  `TIPO_ID` int(11) NOT NULL COMMENT 'ENUM\nPRIMER SEMESTRE\nSEGUNDO SEMESTRE',
  PRIMARY KEY (`ID`,`TIPO_ID`),
  KEY `fk_PERIODO_ACADEMICO_TIPO1_idx` (`TIPO_ID`),
  CONSTRAINT `fk_PERIODO_ACADEMICO_TIPO1` FOREIGN KEY (`TIPO_ID`) REFERENCES `tipo` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;

CREATE TABLE `persona` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PRIMER_NOMBRE` varchar(45) COLLATE latin1_spanish_ci NOT NULL,
  `SEGUNDO_NOMBRE` varchar(45) COLLATE latin1_spanish_ci DEFAULT NULL,
  `PRIMER_APELLIDO` varchar(45) COLLATE latin1_spanish_ci NOT NULL,
  `SEGUNDO_APELLIDO` varchar(45) COLLATE latin1_spanish_ci DEFAULT NULL,
  `CEDULA` varchar(11) COLLATE latin1_spanish_ci DEFAULT NULL,
  `TELEFONO1` int(10) NOT NULL,
  `TELEFONO2` int(10) DEFAULT NULL,
  `DIRECCION1` varchar(500) COLLATE latin1_spanish_ci NOT NULL,
  `DIRECCION2` varchar(45) COLLATE latin1_spanish_ci DEFAULT NULL,
  `NACIONALIDAD` varchar(45) COLLATE latin1_spanish_ci NOT NULL,
  `FECHA_INGRESO` date NOT NULL,
  `FECHA_INACTIVO` date DEFAULT NULL,
  `ACTIVO` int(1) NOT NULL,
  `PASAPORTE` varchar(45) COLLATE latin1_spanish_ci DEFAULT NULL,
  `PAGOS_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`,`PAGOS_ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`),
  UNIQUE KEY `CEDULA_UNIQUE` (`CEDULA`),
  UNIQUE KEY `PASAPORTE_UNIQUE` (`PASAPORTE`),
  KEY `fk_PERSONA_PAGOS1` (`PAGOS_ID`),
  CONSTRAINT `fk_PERSONA_PAGOS1` FOREIGN KEY (`PAGOS_ID`) REFERENCES `pagos` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;

CREATE TABLE `profesor` (
  `ID` int(11) NOT NULL,
  `FORMACION` varchar(500) COLLATE latin1_spanish_ci DEFAULT NULL,
  `SALARIO` float DEFAULT NULL,
  `PERSONA_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`,`PERSONA_ID`),
  KEY `fk_PROFESOR_PERSONA1` (`PERSONA_ID`),
  CONSTRAINT `fk_PROFESOR_PERSONA1` FOREIGN KEY (`PERSONA_ID`) REFERENCES `persona` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;

CREATE TABLE `profesor_da_materia` (
  `PROFESOR_ID` int(11) NOT NULL,
  `MATERIA_ID` int(11) NOT NULL,
  PRIMARY KEY (`PROFESOR_ID`,`MATERIA_ID`),
  KEY `fk_PROFESOR_has_MATERIA_MATERIA1_idx` (`MATERIA_ID`),
  KEY `fk_PROFESOR_has_MATERIA_PROFESOR1_idx` (`PROFESOR_ID`),
  CONSTRAINT `fk_PROFESOR_has_MATERIA_MATERIA1` FOREIGN KEY (`MATERIA_ID`) REFERENCES `materia` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROFESOR_has_MATERIA_PROFESOR1` FOREIGN KEY (`PROFESOR_ID`) REFERENCES `profesor` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;

CREATE TABLE `seccion` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(45) COLLATE latin1_spanish_ci DEFAULT NULL,
  `POSTFIJO` varchar(1) COLLATE latin1_spanish_ci DEFAULT NULL,
  `PERIODO_ACADEMICO_ID` int(11) NOT NULL,
  `PROFESOR_ID` int(11) NOT NULL,
  `TIPO_ID_ANO_ACADEMICO` int(11) NOT NULL COMMENT '\nENUM : ANO_ACADEMICO\n\nprimero de bachiller\nseptimo de basica\nprimero de basica\n\n',
  PRIMARY KEY (`ID`,`PERIODO_ACADEMICO_ID`,`TIPO_ID_ANO_ACADEMICO`),
  KEY `fk_SECCION_ANO_ACADEMICO1` (`PERIODO_ACADEMICO_ID`),
  KEY `fk_SECCION_PROFESOR1` (`PROFESOR_ID`),
  KEY `fk_SECCION_TIPO1` (`TIPO_ID_ANO_ACADEMICO`),
  CONSTRAINT `fk_SECCION_ANO_ACADEMICO1` FOREIGN KEY (`PERIODO_ACADEMICO_ID`) REFERENCES `periodo_academico` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_SECCION_PROFESOR1` FOREIGN KEY (`PROFESOR_ID`) REFERENCES `profesor` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_SECCION_TIPO1` FOREIGN KEY (`TIPO_ID_ANO_ACADEMICO`) REFERENCES `tipo` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;

CREATE TABLE `tipo` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(45) COLLATE latin1_spanish_ci DEFAULT NULL,
  `CATEGORIA` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;

